In [1]:
import pandas  as pd
import numpy as np
import matplotlib.pyplot as plt

# Loding Dataset

In [2]:
adani = pd.read_csv("ADANIENT.NS.csv")

In [3]:
adani

Date         Open         High          Low        Close  \
0     2016-01-01    45.553741    49.422543    44.872616    49.095600   
1     2016-01-04    48.768658    50.158157    45.907928    46.371094   
2     2016-01-05    46.670792    48.823151    45.880684    48.278248   
3     2016-01-06    47.951309    48.468964    46.480076    46.997730   
4     2016-01-07    46.262115    46.262115    42.502296    43.564854   
...          ...          ...          ...          ...          ...   
1745  2023-01-23  3443.050049  3460.000000  3412.550049  3436.350098   
1746  2023-01-24  3447.449951  3508.000000  3430.000000  3442.000000   
1747  2023-01-25  3422.000000  3428.000000  3315.000000  3388.949951   
1748  2023-01-27  3335.000000  3346.500000  2712.000000  2761.449951   
1749  2023-01-30  2850.000000  3037.550049  2665.000000  2892.850098   

        Adj Close    Volume  
0       47.614208  10963906  
1       44.971912   9408965  
2       46.821522   9801814  
3       45.579639   7093448  
4       42.250347   8919023  
...           ...       ...  
1745  3436.350098    974857  
1746  3442.000000   1518123  
1747  3388.949951   3686439  
1748  2761.449951  14764368  
1749  2892.850098  20947906  

[1750 rows x 7 columns]

# Information About Dataset

In [4]:
adani.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1750 entries, 0 to 1749
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Date       1750 non-null   object 
 1   Open       1750 non-null   float64
 2   High       1750 non-null   float64
 3   Low        1750 non-null   float64
 4   Close      1750 non-null   float64
 5   Adj Close  1750 non-null   float64
 6   Volume     1750 non-null   int64  
dtypes: float64(5), int64(1), object(1)
memory usage: 95.8+ KB


In [5]:
adani.head()

Date       Open       High        Low      Close  Adj Close    Volume
0  2016-01-01  45.553741  49.422543  44.872616  49.095600  47.614208  10963906
1  2016-01-04  48.768658  50.158157  45.907928  46.371094  44.971912   9408965
2  2016-01-05  46.670792  48.823151  45.880684  48.278248  46.821522   9801814
3  2016-01-06  47.951309  48.468964  46.480076  46.997730  45.579639   7093448
4  2016-01-07  46.262115  46.262115  42.502296  43.564854  42.250347   8919023

Changing dtype of date column object to datetime

In [6]:
adani.tail()

Date         Open         High          Low        Close  \
1745  2023-01-23  3443.050049  3460.000000  3412.550049  3436.350098   
1746  2023-01-24  3447.449951  3508.000000  3430.000000  3442.000000   
1747  2023-01-25  3422.000000  3428.000000  3315.000000  3388.949951   
1748  2023-01-27  3335.000000  3346.500000  2712.000000  2761.449951   
1749  2023-01-30  2850.000000  3037.550049  2665.000000  2892.850098   

        Adj Close    Volume  
1745  3436.350098    974857  
1746  3442.000000   1518123  
1747  3388.949951   3686439  
1748  2761.449951  14764368  
1749  2892.850098  20947906

In [7]:
adani["Date"]=pd.to_datetime(adani["Date"])
adani

Date         Open         High          Low        Close  \
0    2016-01-01    45.553741    49.422543    44.872616    49.095600   
1    2016-01-04    48.768658    50.158157    45.907928    46.371094   
2    2016-01-05    46.670792    48.823151    45.880684    48.278248   
3    2016-01-06    47.951309    48.468964    46.480076    46.997730   
4    2016-01-07    46.262115    46.262115    42.502296    43.564854   
...         ...          ...          ...          ...          ...   
1745 2023-01-23  3443.050049  3460.000000  3412.550049  3436.350098   
1746 2023-01-24  3447.449951  3508.000000  3430.000000  3442.000000   
1747 2023-01-25  3422.000000  3428.000000  3315.000000  3388.949951   
1748 2023-01-27  3335.000000  3346.500000  2712.000000  2761.449951   
1749 2023-01-30  2850.000000  3037.550049  2665.000000  2892.850098   

        Adj Close    Volume  
0       47.614208  10963906  
1       44.971912   9408965  
2       46.821522   9801814  
3       45.579639   7093448  
4       42.250347   8919023  
...           ...       ...  
1745  3436.350098    974857  
1746  3442.000000   1518123  
1747  3388.949951   3686439  
1748  2761.449951  14764368  
1749  2892.850098  20947906  

[1750 rows x 7 columns]

In [8]:
adani.shape

(1750, 7)

In [9]:
adani.isnull().sum()

Date         0
Open         0
High         0
Low          0
Close        0
Adj Close    0
Volume       0
dtype: int64

In [10]:
adani.isna().any()

Date         False
Open         False
High         False
Low          False
Close        False
Adj Close    False
Volume       False
dtype: bool

In [11]:
adani.describe()

Date         Open         High          Low  \
count                 1750  1750.000000  1750.000000  1750.000000   
mean   2019-07-19 14:52:48   688.173234   700.569161   675.238559   
min    2016-01-01 00:00:00    32.149174    33.402447    31.713251   
25%    2017-10-10 06:00:00    74.134321    75.891117    72.430996   
50%    2019-07-20 12:00:00   148.150002   152.000000   144.975006   
75%    2021-04-28 18:00:00  1193.587524  1237.750000  1173.500000   
max    2023-01-30 00:00:00  4175.000000  4190.000000  4066.399902   
std                    NaN  1021.967477  1036.977084  1004.148913   

             Close    Adj Close        Volume  
count  1750.000000  1750.000000  1.750000e+03  
mean    688.457278   687.474594  7.511264e+06  
min      32.012947    31.047001  2.482490e+05  
25%      74.392643    73.068065  2.789816e+06  
50%     148.025002   146.764984  4.716164e+06  
75%    1198.837524  1197.533173  8.319164e+06  
max    4165.299805  4165.299805  1.701502e+08  
std    1021.222423  1021.504948  1.019781e+07

In [12]:
print(len(adani))

1750


# Date Column Into Month Formate

In [13]:
adani["Date"]=pd.DatetimeIndex(adani["Date"]).month
data=adani
data.head(50)

Date       Open       High        Low      Close  Adj Close    Volume
0      1  45.553741  49.422543  44.872616  49.095600  47.614208  10963906
1      1  48.768658  50.158157  45.907928  46.371094  44.971912   9408965
2      1  46.670792  48.823151  45.880684  48.278248  46.821522   9801814
3      1  47.951309  48.468964  46.480076  46.997730  45.579639   7093448
4      1  46.262115  46.262115  42.502296  43.564854  42.250347   8919023
5      1  44.681900  45.226803  43.946285  44.681900  43.333683   6409374
6      1  44.136997  45.717213  42.992706  44.872616  43.518646   7610929
7      1  44.872616  45.635475  43.319649  44.028019  42.699535   7187524
8      1  44.572922  46.643543  42.066376  44.055264  42.725952  14813664
9      1  43.019951  44.136997  42.148109  42.393314  41.114155   8517248
10     1  42.720257  43.483116  40.268200  40.540649  39.317390   6162841
11     1  40.213711  40.486160  37.162262  38.197575  37.045013   6988884
12     1  38.987682  40.104729  38.088596  39.505341  38.313320   5936602
13     1  38.442780  39.014927  36.753586  37.489204  36.358017   5302168
14     1  38.361046  39.205643  37.053284  37.925125  36.780788   6301101
15     1  38.497272  40.595142  38.497272  40.186466  38.973900   6412547
16     1  40.567898  41.085552  39.614319  40.377182  39.158859   3702771
17     1  40.758610  40.976570  39.668808  39.914017  38.709663   3456780
18     1  40.131973  40.295444  38.987682  39.260132  38.075508   3743917
19     1  39.260132  39.968506  38.252068  39.696053  38.498280   4584955
20     2  40.077484  42.665768  39.995750  40.622387  39.396660  14301204
21     2  40.431671  40.731365  38.796967  39.260132  38.075508   4281060
22     2  40.404427  40.595142  38.796967  39.205643  38.022663   9088526
23     2  39.614319  40.104729  38.769722  39.369114  38.181206   4395526
24     2  39.396358  40.704121  39.123909  40.159222  38.947475   4563542
25     2  40.567898  43.428627  39.941261  41.140041  39.898701  12827236
26     2  40.567898  41.412495  39.505341  40.867592  39.634472   7145205
27     2  40.322689  40.595142  39.123909  39.423603  38.234055   5444984
28     2  39.505341  39.614319  36.263176  36.998795  35.882408   6162865
29     2  37.543694  37.543694  33.511425  34.982658  33.927105   8247087
30     2  35.854500  37.271244  35.146130  35.609295  34.534832   8626379
31     2  36.181442  36.344910  34.138062  34.356022  33.319374   7678551
32     2  34.410511  34.764698  32.966522  34.356022  33.319374   6460857
33     2  34.873676  35.227863  33.375198  34.110817  33.081566   5831539
34     2  34.110817  34.628471  33.702141  34.301533  33.266529   4855147
35     2  34.764698  34.873676  33.647652  33.947346  32.923031   4339569
36     2  34.219795  34.247044  32.830299  33.184483  32.183186   5223434
37     2  33.075504  34.219795  32.476112  33.293465  32.288883   6110278
38     2  33.647652  33.783875  32.612339  32.803055  31.813271   5504340
39     2  33.266220  33.565914  32.230907  32.966522  31.971802   4739308
40     2  33.075504  33.402447  31.713251  32.012947  31.047001   8277215
41     3  32.149174  33.456936  31.931211  33.102749  32.103916   6846633
42     3  33.783875  34.900925  33.293465  34.029079  33.002304   9313684
43     3  34.328777  34.601227  33.429691  34.056328  33.028728   7706783
44     3  34.328777  35.227863  34.056328  34.437756  33.398643   9013442
45     3  34.601227  35.146130  33.920101  34.900925  33.847836  11091171
46     3  34.601227  36.426647  34.383266  36.181442  35.089714   7364105
47     3  36.535625  36.780830  35.364090  35.527561  34.455566   5795786
48     3  35.527561  36.399403  35.309601  35.663784  34.587681   4388832
49     3  35.990726  36.317665  35.227863  35.827255  34.746216   9639983

# Checking correlation of the whole dataset

In [14]:
data.corr()

Date      Open      High       Low     Close  Adj Close  \
Date       1.000000  0.121326  0.121208  0.122590  0.122184   0.122253   
Open       0.121326  1.000000  0.999848  0.999673  0.999554   0.999554   
High       0.121208  0.999848  1.000000  0.999640  0.999761   0.999761   
Low        0.122590  0.999673  0.999640  1.000000  0.999827   0.999827   
Close      0.122184  0.999554  0.999761  0.999827  1.000000   1.000000   
Adj Close  0.122253  0.999554  0.999761  0.999827  1.000000   1.000000   
Volume    -0.070510 -0.231670 -0.229222 -0.233813 -0.230888  -0.230953   

             Volume  
Date      -0.070510  
Open      -0.231670  
High      -0.229222  
Low       -0.233813  
Close     -0.230888  
Adj Close -0.230953  
Volume     1.000000

# Data Slicing in x and y

In [15]:
x=data.iloc[:,[0,1,2,3,4,6]].values
y=data.iloc[:,[5]].values

In [16]:
x

array([[1.00000000e+00, 4.55537410e+01, 4.94225430e+01, 4.48726160e+01,
        4.90956000e+01, 1.09639060e+07],
       [1.00000000e+00, 4.87686580e+01, 5.01581570e+01, 4.59079280e+01,
        4.63710940e+01, 9.40896500e+06],
       [1.00000000e+00, 4.66707920e+01, 4.88231510e+01, 4.58806840e+01,
        4.82782480e+01, 9.80181400e+06],
       ...,
       [1.00000000e+00, 3.42200000e+03, 3.42800000e+03, 3.31500000e+03,
        3.38894995e+03, 3.68643900e+06],
       [1.00000000e+00, 3.33500000e+03, 3.34650000e+03, 2.71200000e+03,
        2.76144995e+03, 1.47643680e+07],
       [1.00000000e+00, 2.85000000e+03, 3.03755005e+03, 2.66500000e+03,
        2.89285010e+03, 2.09479060e+07]])

In [20]:
x

array([[1.00000000e+00, 4.55537410e+01, 4.94225430e+01, 4.48726160e+01,
        4.90956000e+01, 1.09639060e+07],
       [1.00000000e+00, 4.87686580e+01, 5.01581570e+01, 4.59079280e+01,
        4.63710940e+01, 9.40896500e+06],
       [1.00000000e+00, 4.66707920e+01, 4.88231510e+01, 4.58806840e+01,
        4.82782480e+01, 9.80181400e+06],
       ...,
       [1.00000000e+00, 3.42200000e+03, 3.42800000e+03, 3.31500000e+03,
        3.38894995e+03, 3.68643900e+06],
       [1.00000000e+00, 3.33500000e+03, 3.34650000e+03, 2.71200000e+03,
        2.76144995e+03, 1.47643680e+07],
       [1.00000000e+00, 2.85000000e+03, 3.03755005e+03, 2.66500000e+03,
        2.89285010e+03, 2.09479060e+07]])

In [ ]:
x_train.shape

In [21]:
y

array([[  47.614208],
       [  44.971912],
       [  46.821522],
       ...,
       [3388.949951],
       [2761.449951],
       [2892.850098]])

In [ ]:
y_train.shape

In [ ]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
x_scaled=ss.fit_transform(x)

In [ ]:
print(l1.coef_)

In [ ]:
new=pd.DataFrame(x_scaled)
new

# Spliting the dataset into train and test case

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_scaled,y,test_size=0.2,random_state=11)

In [ ]:
from sklearn.linear_model import LinearRegression
l1=LinearRegression()
l1.fit(x_train,y_train)

In [ ]:
y_pred=l1.predict(x_test)
y_pred

# accuracy score

In [ ]:
from sklearn.metrics import r2_score
score=r2_score(y_test,y_pred)*100
score

In [ ]:
ab=l1.predict([[-1.569368,-0.628986,-0.628107,-0.627941,-0.626254,0.338664]])
ab

In [ ]:
ab1=l1.predict([[-1.569368,-0.628293,-0.631156,-0.630302,-0.631671,0.138085]])
ab1